### ISSUE TITLE
satellite: unknown error

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#452] opened 2021-11-18 13:07 UTC
**Describe the bug**
```
DEBUG:nowcasting_dataset.data_sources.data_source:HRVSatelliteDataSource creating batch 0!
2021-11-18 13:03:03,184 ERROR processID=1693776 Worker process satellite raised exception!
A process in the process pool was terminated abruptly while the future was running or pending. | /home/peter/Github/nowcasting_dataset/nowcasting_dataset/manager.py#L481
NoneType: None
```

**To Reproduce**
run prepear_ml_data.py

**Comment by peterdudfield** [comment] 2021-11-18 13:16
there is also 
```
2021-11-18 13:12:50,243 ERROR processID=1701141 Some NWP data values are NaNs | /home/peter/Github/nowcasting_dataset/nowcasting_dataset/data_sources/datasource_output.py#L62
ERROR:nowcasting_dataset.data_sources.datasource_output:Some NWP data values are NaNs
```

**Comment by JackKelly** [comment] 2021-11-18 13:37
>  process in the process pool was terminated abruptly while the future was running or pending

hmm... not sure what's going on here.... it's perhaps relevant that `leonardo` says it has used all its swap file (which is bad): 

![image](https://user-images.githubusercontent.com/460756/142425518-86cec38d-0cc5-49cd-be6d-680e31d5676d.png)

**Comment by peterdudfield** [comment] 2021-11-18 14:10
ting_dataset/nowcasting_dataset/data_sources/datasource_output.py#L106
WARNING:nowcasting_dataset.data_sources.datasource_output:Some Satellite data values are equal to -1

I can also see some satellite values set to -1, which I think was the filled nan values

**Comment by JackKelly** [comment] 2021-11-18 14:13
I think that maybe there are three separate issues here?

1. "A process in the process pool was terminated abruptly" which I'm gonna guess was caused by `leonardo` running out of RAM and swap space?
2. Some NWP values are NaN
3. Some Satellite values are -1?

**Comment by jacobbieker** [comment] 2021-11-18 14:28
Ah, for the satellite data, I did set NaNs to -1 as that was what was happening before, but there shouldn't be any because I checked for NaNs and nulls right before writing to disk, but I guess some got through?

**Comment by peterdudfield** [comment] 2021-11-19 13:52
Ive made #481 for the NWP nans

**Comment by JackKelly** [comment] 2021-11-22 11:20
Thanks!

I've made #484 for the `-1` in satellite data.

I assume the `A process in the process pool was terminated abruptly` issue has gone away now, and that we can close this issue now?  I'll close for now but please re-open if the `A process in the process pool was terminated abruptly` issue still persists!

**Closed by JackKelly** 2021-11-22 11:20 UTC
Labels: bug
