### ISSUE TITLE
O validation items

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#441] opened 2021-11-18 09:54 UTC
**Describe the bug**
```
n. | /home/peter/Github/nowcasting_dataset/nowcasting_dataset/manager.py#L185
DEBUG:nowcasting_dataset.manager:Creating 10 batches x 32 examples per batch = 320 examples for validation.
Traceback (most recent call last):
  File "/home/peter/Github/nowcasting_dataset/scripts/prepare_ml_data.py", line 79, in <module>
    main()
  File "/home/peter/miniconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/peter/miniconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/peter/miniconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/peter/miniconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/peter/Github/nowcasting_dataset/nowcasting_dataset/utils.py", line 155, in inner_func
    return func(*args, **kwargs)
  File "/home/peter/Github/nowcasting_dataset/scripts/prepare_ml_data.py", line 71, in main
    manager.create_files_specifying_spatial_and_temporal_locations_of_each_example_if_necessary()
  File "/home/peter/Github/nowcasting_dataset/nowcasting_dataset/manager.py", line 189, in create_files_specifying_spatial_and_temporal_locations_of_each_example_if_necessary
    df_of_locations = self.sample_spatial_and_temporal_locations_for_examples(
  File "/home/peter/Github/nowcasting_dataset/nowcasting_dataset/manager.py", line 290, in sample_spatial_and_temporal_locations_for_examples
    shuffled_t0_datetimes = np.random.choice(t0_datetimes, size=n_examples)
  File "mtrand.pyx", line 915, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
```

**To Reproduce**
run script preapare_ml_data.py

**Comment by JackKelly** [comment] 2021-11-18 09:56
Dupe of #442 :slightly_smiling_face:

**Closed** 2021-11-18 11:57 UTC
Labels: bug
